### ISSUE TITLE
KeyError: 'norm_type' When Using Diffusers pipeline

### ISSUE THREAD

**Issue by JasperChennn** [microsoft/VQ-Diffusion#47]
When I use the pipeline to load vq-diffusion-ithq, it occurs error:
```
Traceback (most recent call last):
  File "/share/vq-diffusion/test.py", line 12, in <module>
    pipeline = VQDiffusionPipeline.from_pretrained("/share/pretrained_models/vq-diffusion-ithq", torch_dtype=torch.float16)
  File "/share/anaconda3/envs/ro/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/share/anaconda3/envs/ro/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 876, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/share/anaconda3/envs/ro/lib/python3.10/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 700, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/share/anaconda3/envs/ro/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/share/anaconda3/envs/ro/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 1201, in from_pretrained
    remapped_class = _fetch_remapped_cls_from_config(config, cls)
  File "/share/anaconda3/envs/ro/lib/python3.10/site-packages/diffusers/models/model_loading_utils.py", line 85, in _fetch_remapped_cls_from_config
    remapped_class_name = _CLASS_REMAPPING_DICT.get(previous_class_name).get(config["norm_type"], None)
KeyError: 'norm_type'
```

**Comment by hakanmuluk** [comment]
hello, could you solve it @PoisonKiller

**Comment by yutchina** [comment]
> hello, could you solve it [@PoisonKiller](https://github.com/PoisonKiller)

hello, could you solve it？
